#!/bin/bash

args=$@

# This will set the $DIR equal to wherever this script is
# living.
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

set -e

# pegasus bin directory is needed to find keg
export PEGASUS_LOCAL_BIN_DIR=`pegasus-config --bin`
export PATH=/study3/reference/pegasus-dev/SOFTWARE/pegasus/default/bin:$PATH

# generate the dax
export PYTHONPATH=`pegasus-config --python`
export EXECUTABLE_DIR=${DIR}/executables

${DIR}/dipa.py $args
